### PR TITLE
Screenshot

### PR DESCRIPTION
**Pull request by vipul-21**
This PR includes the screenshot of the scene with the svg overlay.
@svoinea The code for adding the watermark at the bottom left of the screenshot and the scale has been modified. I have commented some part of it. Please do take a look at it.

### CODE REVIEW

**Comment by svoinea** [comment]
I have tested on `rbk-dev` with:
```
chaise_pull_checkout annotation-list
openseadragon_pull_checkout Screenshot
chaise_install
openseadragon_install
```
I have tested a `czi` and a `tif` file.

In both I see the `Show Annotations` and `Show Channels` menus disabled. Is it intentionally?

The `Take a Screenshot` for the `tif` file does not work (the file is not saved). It adds just the watermark as you can see in:

tiff

For the `czi` file, the file can be saved:
czi

I'm not sure if the position of the watermark in both the `tif` and `czi` files is the right one.

**Comment by vipul-21** [comment]
@svoinea Updated the PR.
1) The Show Annotations and Show Channels menus were disabled because there were no annotations or channels to show for.
2) I have fixed tiff screenshot.
3) The position of watermark is also fixed.
Also, since there are no available annotation on the dev server currently, this is the link for the [screenshot with svg overlay.](https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=16-2EC6?url=/iiif/2/https%3A%2F%2Fderiva-imaging.isi.edu%2Fimages%2F20160707-hKDCS19_133-JAM-0-30-000-3.tif/info.json&url=/~vipul/chaise-demo/data/20160707-hKDCS19-133-JAM-0-30-00_scene3_fixed.svg&channelName=TL%20Brightfield&meterScaleInPixels=455504&waterMark=GUDMAP.org)

**Comment by svoinea** [comment]
I have tried again the test on `rbk-dev` with the `chaise annotation-list` and `openseadragon Screenshot` branches.

For the `*.tiff` files, the download still seems not working.

The watermark should be placed on the bottom left corner of the `viewer`. As far as I know, that was a requirement. See in the below screenshots the differences between the watermark on `rbk-dev` and `rbk-www`:
14-47WE_dev

14-47WE_www

I don't know what you mean by `no channels`. The `.czi` file with the `RID=14-47WE` has for example a channel.

Also, if there are `no annotations`, should it not be an option to create new annotations?

**Comment by vipul-21** [comment]
@svoinea I am trying to fix the screenshot issue. Can we please try and merge this [PR](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/8. This PR does not have the new screenshot feature.

**Comment by vipul-21** [comment]
@svoinea I've updated the code. Following are the links which were tested: 
1. [Tiff images with svg overlay](https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=16-2EC6?url=/iiif/2/https%3A%2F%2Fderiva-imaging.isi.edu%2Fimages%2F20160707-hKDCS19_133-JAM-0-30-000-3.tif/info.json&url=/~vipul/chaise-demo/data/20160707-hKDCS19-133-JAM-0-30-00_scene3_fixed.svg&channelName=TL%20Brightfield&meterScaleInPixels=455504&waterMark=GUDMAP.org) 
2. [Tiff images with watermark](https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=16-1ZYT?waterMark=gudmap.org)
3. [Tiff images without watermark](https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=N-FGK2)
4. [CZI images with watermark](https://dev.gudmap.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=14-47WE?waterMark=gudmap.org)
5.  [CZI images without watermark](https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=14-47WE)

The screenshot for the above mentioned scenarios is working fine. 
Regarding other issues mentioned in above comments:
1) Channel list visibility issue- resolved in this [PR](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/10).
2) Scale bar not present in the screenshot - resolved in this updated PR.
3) @hongsudt If there are `no annotations`, should it not be an option to create new annotations ?

**Comment by svoinea** [comment]
Please double check with @hongsudt:

- the location of the watermark and scalebar
- the visibility of the watermark

My understanding is:

- the location of the watermark and scalebar are relative to the `viewer` and not to the `screen`.
- the watermark is visible only on the screenshot and not on the screen. Your second example leaves the watermark on the screen once you click the `Take a Screenshot` button.

**Comment by vipul-21** [comment]
@svoinea Can you please share the details of the browser and OS you're seeing the issue for second example. In my browser(chrome Version 79.0.3945.130), it is working fine.

**Comment by svoinea** [comment]
@vipul-21 It happens on `Linux` with `Firefox` version `68`.
I'm not sure why on my `MAC` with `Chrome` version `79`, I'm getting a `Network error` while clicking the `Take a Screenshot` button.

**Comment by vipul-21** [comment]
- Tested on `Mac` works fine for chrome, Firefox and Safari.
- Tested on  `Windows` works fine for chrome and Firefox. Edge is showing the same behavior as mentioned by Serban i.e. Second example leaves the watermark on the screen once you click the Take a Screenshot button.

**Comment by rastogi-bhavya** [comment]
While testing this branch I had some doubts and issue. Need some help with these:
4,5 - what is a thumbnail
Scalebar - what does it look like?
8 - the scalebar is showing where as the testcase says that it shouldn't
9 - the scale shows 1µm instead of 50µm
12 - scalebar show 1 mm instead of 2mm
13- unclear what is mean? what is attribution?
17,18,19 - what does it mean?
21,24 - scale not coming in the screenshot
28 - scale shown
29, 30 - not working with my username (404 error)
32 - does annotation button mean show/hide annotation, need a link for an image with no annotations
Issue - show annotation -> highlight annotation -> hide annotation ==> the highlight annotation is still active. Should the highlight annotation be deselected?
"Under all Display = All situation, when users click the hide button of an item, the annotation should disappear on the openseadragon-viewer and the item should remain emphasized and the eye icon should be crossed out"
what does this mean?
39 - the 'X' button is not placed properly
41 - Issue - click show all -> hide anyone of the annotations ==> should the "show all" still be ticked?

**Comment by carlkesselman** [comment]
Scale bar is something we have had issues with before and configuration will depend on correct metadata.  Would be good to sort through and make sure that is it behaving properly in all cases, and to be clear what it means to behave properly.  So view this all with some suspicion!

Carl

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On May 20, 2020, 3:19 PM -0700, Bhavya Rastogi <notifications@github.com>, wrote:

While testing this branch I had some doubts and issue. Need some help with these:
4,5 - what is a thumbnail
Scalebar - what does it look like?
8 - the scalebar is showing where as the testcase says that it shouldn't
9 - the scale shows 1µm instead of 50µm
12 - scalebar show 1 mm instead of 2mm
13- unclear what is mean? what is attribution?
17,18,19 - what does it mean?
21,24 - scale not coming in the screenshot
28 - scale shown
29, 30 - not working with my username (404 error)
32 - does annotation button mean show/hide annotation, need a link for an image with no annotations
Issue - show annotation -> highlight annotation -> hide annotation ==> the highlight annotation is still active. Should the highlight annotation be deselected?
"Under all Display = All situation, when users click the hide button of an item, the annotation should disappear on the openseadragon-viewer and the item should remain emphasized and the eye icon should be crossed out"
what does this mean?
39 - the 'X' button is not placed properly
41 - Issue - click show all -> hide anyone of the annotations ==> should the "show all" still be ticked?

**Pull request merged**
