### PR TITLE
Merging the codes

### PR DESCRIPTION
**Pull request by vipul-21**
This PR is dependent on the chaise [PR](https://github.com/informatics-isi-edu/chaise/pull/1890). It resolves the issues #11.
Test cases :  https://github.com/informatics-isi-edu/chaise/wiki/Viewer-regression-tests

### CODE REVIEW

**Comment by iamyle0710** [comment]
Changes are good overall, just found some minor differences when I tested the cases. 

**[Zoom and Pan]**
1. thumbnail shown in the current version, but not in the staging version(Not sure if this is an issue)
- Current version : 
https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=16-2GN8?waterMark=rebuildingakidney.org&meterScaleInPixels=3624000
- Staging version : https://staging.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=16-2GN8?waterMark=rebuildingakidney.org&meterScaleInPixels=3624000

**[Scale bar]**
1. Scalebar is shown in the staging version, not in the current version
- Current version v.s  Staging version : https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=14-47YP?waterMark=gudmap.org
https://staging.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=14-47YP?waterMark=gudmap.org
- Current version v.s  Staging version : https://dev.rebuildingakidney.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=14-47YP?waterMark=gudmap.org
https://staging.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=14-47YP?waterMark=gudmap.org


**[Screenshots]**
1. changes are good. It works as in the staging version
- checked with following file formats: czi, tiff from image server, jpg

**[Multi-channels]**
1. when I adjust the contrast to 80, it doesn't seem to have same effect as in the staging version
- Current Version : https://dev.gudmap.org/~mingyi/chaise/viewer/#2/Gene_Expression:Image/id=16-2GM0?waterMark=gudmap.org
image

- Staging Version : https://staging.gudmap.org/chaise/viewer/#2/Gene_Expression:Image/id=16-2GM0?waterMark=gudmap.org
image

**Comment by hongsudt** [comment]
All these issues need to be addressed especially the scale bar..

Under zoom and pan, we should figure out why the thumbnail is shown; but more importantly the color in the thumbnail is different from the actual image.. This is bad since it is confusing.




________________________________

**Comment by vipul-21** [comment]
I've updated the PR.
1. Resolved the thumbnail issue.
2. In the scale issue, for xml on [staging](https://staging.rebuildingakidney.org/data/Gene_Expression/2018/c15ed4a97f1ea32f9f2faec649d587e6/AF555/ImageProperties.xml) the response include `meterScaleInPixels`. But in the [dev](https://dev.rebuildingakidney.org/data/Gene_Expression/2018/c15ed4a97f1ea32f9f2faec649d587e6/AF555/ImageProperties.xml), it does not include the `meterScaleInPixels` that is why it is not shown on dev.
3. Multichannel issue with respect to contrast.

**Comment by svoinea** [comment]
I have tested the cases specified on the wiki https://github.com/informatics-isi-edu/chaise/wiki/Viewer-regression-tests page using my home `public_html` directory with:
 - chaise `annotation-list`
 - ermrestjs `master`
 - openseadragon-viewer `multiple-annotations`

Two cases need attention:
 - case `#2`: It seems that for the `tiff` files, zoom in/out is not working for the mouse button clicks (https://dev.rebuildingakidney.org/~serban/chaise/viewer/#2/Gene_Expression:Image/id=14-3RDT?waterMark=gudmap.org)
 - case `#13`: It seems that the `meterScaleInPixels` from the URL does not overwrite the one specified in the metadata (the `ImageProperties.xml` file) - (https://dev.gudmap.org/~serban/chaise/viewer/#2/Gene_Expression:Image/id=14-47ZA&meterScaleInPixels=3511900 - expected the scalebar to show `50 µm`; it is showing `1 mm`)

**Comment by vipul-21** [comment]
@svoinea The case `#2`: I've fixed the situation.
case `#13`: I checked the [production](https://www.gudmap.org/chaise/viewer/#2/Gene_Expression:Image/id=14-47ZA&meterScaleInPixels=3511900), it seems to work in the same manner [here]((https://dev.gudmap.org/~vipul/chaise/viewer/#2/Gene_Expression:Image/id=14-47ZA&meterScaleInPixels=3511900)) as well.

**Comment by svoinea** [comment]
I have retested issues `#2` and `#13` and they work as expected.

**Comment by vipul-21** [comment]
@hongsudt I have updated the PR with the cross on the channel list.

**Comment by svoinea** [comment]
I have applied the latest changes on my `public_html` directory and the test case `#29` looks good to me.

Test case `#31` remains open, the channel button remaining enabled, and showing `No channels found` when you click it.

**Pull request merged**
