### PR TITLE
Svg on tif

### PR DESCRIPTION
**Pull request by vipul-21**
The openseadragon-viewer app updated by @iamyle0710.

### CODE REVIEW

**Comment by svoinea** [comment]
rbk-dev
`rbk-dev`

rbk-staging
`rbk-staging`

The modified `openseadragon-viewer/css/viewer.css` file affects the display of the channels as you might see in the attached images.

The URLs are respectively https://dev.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=14-47WE?waterMark=gudmap.org (with the new `viewer.css` file from the `svg-on-tif` branch), and https://staging.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=14-47WE?waterMark=gudmap.org (with the current `viewer.css` file from `master`).

In the new `viewer.css`, the channels `div` is not top aligned and a little bit left truncated.

Otherwise, it looks good to me.

**Comment by vipul-21** [comment]
@svoinea  I tested the link you mentioned above. It works fine in Chrome Version 78.0.3904.108, Safari 13.0.3 and Firefox 70.0.1. Could let me know how to replicate the issue ?

**Comment by svoinea** [comment]
@vipul-21 I have placed the https://github.com/informatics-isi-edu/openseadragon-viewer/blob/svg-on-tif/css/viewer.css file into the `/var/www/html/openseadragon-viewer/css` directory of `rbk-dev`.

The `rbk-dev` is doing hourly updates (usually in the first `10` minutes of every hour), and during that update, the `viewer.css` file is replaced with the one on `master`.

So, make sure you have the `viewer.css` file from the `svg-on-tif` branch when you are testing the link I mentioned.

**Comment by vipul-21** [comment]
Updated the PR.

**Pull request merged**
